apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: quantity_db
        - name: MYSQL_USER
          value: springuser
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: root
        args: ["--skip-name-resolve"]
---
apiVersion: v1
kind: Service
metadata:
  name: qma-backend
spec:
  selector:
    app: qma-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qma-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qma-backend
  template:
    metadata:
      labels:
        app: qma-backend
    spec:
      containers:
      - name: qma-backend
        image: 054014031154.dkr.ecr.ap-south-2.amazonaws.com/qma-backend:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-db:3306/quantity_db
        - name: SPRING_DATASOURCE_USERNAME
          value: springuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: qma-frontend
spec:
  type: LoadBalancer
  selector:
    app: qma-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qma-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qma-frontend
  template:
    metadata:
      labels:
        app: qma-frontend
    spec:
      containers:
      - name: qma-frontend
        image: 054014031154.dkr.ecr.ap-south-2.amazonaws.com/qma-frontend:latest
        env:
        - name: DANGEROUSLY_DISABLE_HOST_CHECK
          value: "true"
